version: "3.9"

services:
  go_app:
    image: goproject:latest
    build: .
    ports:
      - "81:81"
    depends_on:
      - go_db
  go_db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: go
      POSTGRES_DB: go
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}